/*
 * Expansion batch — fills gaps found in a coverage audit.
 *
 * Split out of study-data.js in phase 2026-09-01. outputs/study-data.js is
 * the barrel every importer still uses; nothing imports this file directly
 * except its siblings.
 */

/* ------------------------------------------------------------------ *
 * Expansion batch — fills gaps found in a coverage audit
 * ------------------------------------------------------------------ */

export const EXPANSION_ITEMS = [
  {
    id: 'hss2011-terminology-word-parts',
    subject: 'HSS2011', unit: 'hss.term', type: 'matching',
    title: 'Word parts — prefixes, suffixes and roots',
    tags: ['terminology', 'foundation', 'high-yield'],
    lesson: {
      explanation: 'Anatomical terms are built from roots, prefixes and suffixes. The root usually names an organ, tissue or condition; the prefix or suffix describes it. Once you can take a term apart, you can read one you have never met. The subject supplies a word-part list prepared by the Module 0 lecturer: prefixes of position such as epi- (above, upon), hypo- (below; also deficient), inter- (between), peri- and circum- (around), pre- (before, in front of), post- (behind, after), retro- (backward), ab- (away from), para- (near, beside; also abnormal); roots of place such as cardi/o (heart), oste/o (bone), arthr/o (joint), my/o (muscle), neur/o (nerve), nephr/o and ren/o (kidney), pulmon/o (lung), crani/o (skull), cost/o (rib), later/o (side), medi/o (middle), anter/o (front), poster/o and dors/o (back), ventr/o (belly side), proxim/o (near), infer/o (downward); and suffixes of process such as -graphy (process of recording), -graph (instrument to record), -scopy (process of viewing), -tomy (incision, cutting), -stomy (new opening), -itis (inflammation), -algia and -dynia (pain), -megaly (enlargement), -osis (abnormal condition), -emia (blood condition), -pathy (disease process).',
      plain: 'Anatomical words are built from roots, prefixes and suffixes, like building blocks. The root names the thing — heart (cardi/o), bone (oste/o), joint (arthr/o) — and a prefix or suffix changes the meaning, e.g. peri- means around and -itis means inflammation. Learn the parts and you can read a term you have never met. The course gives you a word-part list organised as prefixes of position, roots of place and suffixes of process.',
      keyFacts: [
        'Root = organ, tissue or condition. Prefix/suffix = describes the root.',
        'epi- above/upon · hypo- below or deficient · inter- between · circum- around · pre- before · post- after · retro- backward · ab- away from.',
        'cardi/o heart · oste/o bone · arthr/o joint · my/o muscle · neur/o nerve · nephr/o and ren/o kidney · crani/o skull · cost/o rib.',
        'later/o side · medi/o middle · anter/o front · poster/o and dors/o back · ventr/o belly side · proxim/o near · infer/o downward.',
        '-graphy process of recording · -graph the instrument · -scopy process of viewing · -itis inflammation · -algia pain · -megaly enlargement · -osis abnormal condition · -emia blood condition.',
        'hypertension = hyper- (high/over) + tension (pressure) = abnormally high blood pressure.',
      ],
      prerequisites: ['hss2011-terminology-directional-pairs'],
      examples: ['Radiography itself is a word part exercise: radio- (radiation) + -graphy (process of recording).'],
    },
    memory: {
      chunking: 'Three slots, always in the same order: prefix (where/how much) → root (what) → suffix (what is happening to it). Read any term left to right in those slots.',
      wordOrigin: 'The directional roots are the Latin words behind the directional terms you already know — proxim/o is proximal, later/o is lateral, medi/o is medial. You have half of this list already.',
      comparison: '-graphy is the process, -graph is the machine, -gram is the result. Radiography is what you do, the radiograph is what you get.',
      teachBack: 'Take a term you have never seen — say "costochondritis" — and split it out loud: cost/o rib + chondr/o cartilage + -itis inflammation. If you can do that cold, you have the skill.',
    },
    practice: [
      { type: 'matching', prompt: 'Match each prefix to its meaning.',
        pairs: [['epi-', 'Above, upon'], ['hypo-', 'Below; deficient'], ['inter-', 'Between'], ['retro-', 'Backward']],
        explanation: 'These are the meanings given in the subject word-part list.' },
      { type: 'matching', prompt: 'Match each suffix to its meaning.',
        pairs: [['-itis', 'Inflammation'], ['-algia', 'Pain'], ['-megaly', 'Enlargement'], ['-graphy', 'Process of recording']],
        explanation: 'Note -graphy is the process; -graph is the instrument that records.' },
      { type: 'typed', prompt: 'Which root means bone?', accept: ['oste/o', 'osteo', 'oste', 'oss/i', 'osse/o'],
        explanation: 'oste/o (also oss/i, osse/o). It is the root inside "osteology", the study of bones.' },
      { type: 'typed', prompt: 'Split the word "radiography" into its two parts and give the meaning of each.', accept: ['radio- radiation, -graphy process of recording', 'radio radiation graphy recording', 'radio = radiation, graphy = process of recording'],
        explanation: 'radio- is the radial spread-out of energy, i.e. radiation; -graphy is the process of recording. The HTI17103 lecture makes exactly this split.' },
      { type: 'mcq', prompt: 'A term ending in -ostomy describes what?', options: ['An incision', 'A new opening', 'An instrument to view', 'An abnormal condition'], answer: 1,
        explanation: '-stomy is a new opening. -tomy is incision or cutting, -scope is the instrument to view, -osis is an abnormal condition.' },
    ],
    application: [
      { type: 'scenario', prompt: 'You meet the term "pericarditis" for the first time in a report. Work out what it means from its parts, and say which structure from your thorax study it involves.',
        model: 'peri- (around) + cardi/o (heart) + -itis (inflammation) — inflammation of the structure around the heart, which is the pericardium. That is the sac you already distinguish from the epicardium, which is the heart wall’s own outer layer.',
        rubric: ['Splits the term into all three parts', 'Gives the meaning of each part', 'Identifies the pericardium and separates it from the epicardium'] },
    ],
    commonMistakes: [
      'Confusing -graphy (the process), -graph (the instrument) and -gram (the record produced).',
      'Reading hypo- only as "below in position" — the list also gives it as "deficient, below, under", which is how it is used in words like hypoglycaemia.',
    ],
    skills: [
      'hypo- is the word-part list\'s double agent: the same prefix means below in position AND deficient in amount — the deficiency sense is the one inside hypoglycaemia, and reading hypo- only as "below" loses half its uses. Most prefixes in the list carry one meaning; this one carries two, which is what makes it the trap.',
      '-graphy, -graph and -gram are one suffix in three grammatical roles — the process, the instrument, the record produced — not interchangeable spellings of one word. The same one-letter discipline separates -tomy (incision) from -stomy (new opening): in this terminology a single letter can carry a whole meaning.',
      'A correct split does anatomical work, not just translation: pericarditis parses to inflammation of the structure around the heart — the pericardium — which is exactly the sac the thorax material separates from the epicardium, the heart wall\'s own outer layer. Read the word parts as anatomy, not as a translation exercise.',
    ],
    selfCheck: 'Split costochondritis and pericarditis cold into all three parts with meanings, and correctly classify all three of -graphy, -graph and -gram.',
    sourceRefs: [{ ref: 'hss.wordparts', location: 'Full word-part list, prepared by Josephine Lau (HTI)' }, { ref: 'hss.orientation', location: 'Opening paragraph on roots, prefixes and suffixes' }],
  },
  {
    id: 'hss2011-pastpaper-joints-articulations',
    subject: 'HSS2011', unit: 'hss.joints', type: 'cloze',
    title: 'Past-paper drill — joints and articulations',
    tags: ['joints', 'exam', 'high-yield'],
    lesson: {
      explanation: 'These are fill-in-the-blank questions taken from the topic-sorted past-paper bank, kept only where the answer is independently confirmed by a current HSS2011 lecture or the revision-exercise answer key. They are worth drilling because they show how the same handful of facts — joint classification, which bones meet where, and the names of the resulting joints — get asked year after year in slightly different wording.',
      keyFacts: [
        'The humerus articulates with the ulna and radius to form the elbow joint.',
        'The intervertebral disc is a cartilaginous joint, between the vertebral bodies of two adjacent vertebrae.',
        'A sutural joint of the skull is a fibrous joint.',
        'The medial end of the clavicle meets the sternum at the sternoclavicular joint.',
        'The glenoid fossa articulates with the head of the humerus to form the shoulder joint.',
        'The carpal bones articulate with the radius to form the radiocarpal (wrist) joint.',
        'The femoral and tibial condyles are the articular parts of the knee joint.',
        'The patella is the largest sesamoid bone in the body.',
      ],
      prerequisites: ['hss2011-joints-classification'],
      examples: [],
    },
    memory: {
      chunking: 'Almost every one of these is the same question in disguise: name the two bones, then name the joint. Answer in that order and the wording stops mattering.',
      comparison: 'Three joint classes, three giveaway words in the question. "Suture" means fibrous. "Disc" means cartilaginous. Anything with a named cavity or free movement means synovial.',
      teachBack: 'Take any joint in your own body, say which two bones form it and which class it belongs to, out loud. If you can do ten in a row you have covered most of what this bank asks.',
    },
    practice: [
      { type: 'cloze', prompt: 'The ______ is a long bone of the arm. It articulates with the ulna and radius to form the ______ joint.', accept: ['humerus; elbow', 'humerus, elbow', 'humerus and elbow'],
        explanation: 'Humerus, elbow. The lecture shows the humeral trochlea meeting the trochlear notch of the ulna and the capitulum meeting the head of the radius.',
        src: { ref: 'hss.4.3', location: 'Slide "Elbow Joint (Anterior View)", Fig. 8-4c' } },
      { type: 'cloze', prompt: 'The intervertebral disc is typed as a ______ joint, located between the vertebral ______ of two adjacent vertebrae.', accept: ['cartilaginous; bodies', 'cartilaginous, bodies', 'cartilaginous and bodies', 'symphysis; bodies'],
        explanation: 'Cartilaginous, bodies. The lecture names the inter-body joints of the spine as symphyses — secondary cartilaginous joints where two bones are joined by fibrocartilage.',
        src: { ref: 'hss.4.1', location: 'Slide "Cartilaginous joints — Symphyses"' } },
      { type: 'cloze', prompt: 'The sutural joint of the skull is typed as a ______ joint.', accept: ['fibrous'],
        explanation: 'Fibrous. Sutures articulate by process and indentation with the bones bound by fibrous connective tissue, which is why they permit the least movement of any joint.',
        src: { ref: 'hss.4.1', location: 'Slide "Fibrous joints — Sutures"' } },
      { type: 'cloze', prompt: 'The medial end of the clavicle articulates with the sternum to form the ______ joint.', accept: ['sternoclavicular', 'sternoclavicular joint'],
        explanation: 'Sternoclavicular — and it is the only bony joint linking the upper limb back to the axial skeleton.',
        src: { ref: 'hss.4.3', location: 'Slide "Joints Around Shoulder Region", Fig. 8-2' } },
      { type: 'cloze', prompt: 'The carpal bones articulate with the radius to form the ______ joint.', accept: ['radiocarpal', 'wrist', 'radiocarpal (wrist)', 'wrist joint', 'radiocarpal joint'],
        explanation: 'The radiocarpal, or wrist, joint. Its articular bones are the radius with the scaphoid, lunate and triquetrum.',
        src: { ref: 'hss.m0.1718', location: 'L1 p45 right wrist (radiocarpal) joint' } },
      { type: 'cloze', prompt: 'The largest sesamoid bone in the human body is the ______.', accept: ['patella', 'kneecap'],
        explanation: 'The patella. A sesamoid bone develops within a tendon and alters the direction of its pull.',
        src: { ref: 'hss.4.1', location: 'Slide "Sesamoid bones"' } },
      { type: 'cloze', prompt: 'The outer surfaces and walls of bones are composed of ______ bone.', accept: ['compact'],
        explanation: 'Compact bone — a dense solid mass forming the outer surface layer of all bones. Cancellous (spongy) bone lies internally.',
        src: { ref: 'hss.revans', location: 'Module 4.1, Fill-in-blanks 1' } },
      { type: 'cloze', prompt: 'Tip-to-tip attachment of the thumb with any one of the fingers is called ______.', accept: ['opposition'],
        explanation: 'Opposition — and its opposite is reposition. Both happen at the carpo-metacarpal joint of the thumb. This question appears in the past-paper bank in almost the same words as the Module 0 slide.',
        src: { ref: 'hss.revans', location: 'Module 0, Fill-in-blanks 1' } },
    ],
    application: [
      { type: 'scenario', prompt: 'The same bank asks, in different years, for "the joint formed by the carpal bones and the radius" and for "the articular bones of the right wrist joint". What single piece of knowledge answers both, and what does that tell you about how to revise this topic?',
        model: 'Knowing that the radiocarpal joint is formed by the radius with the scaphoid, lunate and triquetrum answers both — one asks for the joint name, the other for its components. The lesson is to learn each joint as a small package (name, the bones, the class, the movements) rather than as an isolated fact, because the examiner can enter that package from any side.',
        rubric: ['Identifies the radiocarpal joint and its articular bones', 'Notes the two questions probe the same package from different directions', 'Draws the revision conclusion'] },
    ],
    commonMistakes: [
      'Answering "cartilage" when the question asks for the joint TYPE — the answer wanted is cartilaginous, or more precisely a symphysis.',
      'Giving the acromioclavicular joint for the medial end of the clavicle; medial means the sternal end, so it is the sternoclavicular joint.',
    ],
    skills: [
      '"Cartilage" is the trap answer on the intervertebral disc question: the disc is typed as a cartilaginous joint — a symphysis between the vertebral bodies — and naming the tissue instead of the joint class drops the mark. The class words end in -ous (fibrous, cartilaginous, synovial); the tissue name does not.',
      'The giveaway word settles the joint class before any recall does: suture means fibrous, disc means cartilaginous, and a named cavity or free movement means synovial. Medial is the same kind of deciding word on the clavicle question — the medial end meets the sternum at the sternoclavicular joint, the upper limb\'s only bony joint with the axial skeleton, while the acromioclavicular hangs off the lateral end.',
      'The bank asks one fact through several doors: "the joint formed by the carpal bones and the radius" and "the articular bones of the right wrist joint" are the same radiocarpal package — name, bones, class, movements — entered from different sides, which is why the package, not the wording, is the thing to own.',
    ],
    selfCheck: 'Run the eight cloze prompts of this item from a blank page, then take ten joints of your own body and state each one’s two bones and class out loud without a miss.',
    sourceRefs: [
      { ref: 'hss.ga.topics', location: 'Skeletal Joint and Muscular systems; Upper Limbs and Lower Limbs — questions 2006-07 to 2011-12' },
      { ref: 'hss.4.1', location: 'Joint classification and bone structure slides' },
      { ref: 'hss.4.3', location: 'Upper and lower limb bones and joints' },
      { ref: 'hss.revans', location: 'Module 0 and Module 4.1 answer keys — used to verify every answer above' },
    ],
  },
  {
    id: 'hss2011-joints-synovial-types',
    subject: 'HSS2011', unit: 'hss.joints', type: 'comparison',
    title: 'The six synovial joint types, with examples',
    tags: ['joints', 'high-yield'],
    lesson: {
      explanation: 'Synovial joints are the most common in the body and come in six types, classified by the shape of the articulating surfaces and by how many axes of movement they allow. Hinge joints move in one plane only — the elbow, where the humeral trochlea sits in the trochlear notch of the ulna, and the interphalangeal joints. Pivot joints allow rotation about a single axis — the median atlanto-axial joint, where the atlas turns on the dens of the axis, and the proximal radioulnar joint that carries supination and pronation. Condylar joints allow movement in two planes — the radiocarpal (wrist) joint and the metacarpophalangeal joints. Saddle joints also allow two planes plus opposition — the carpo-metacarpal joint of the thumb. Plane joints allow gliding — the apophyseal (facet) joints of the vertebral column and the acromioclavicular joint. Ball-and-socket joints allow movement in all three planes — the glenohumeral joint, where the humeral head sits in the shallow glenoid fossa, and the hip joint, where the femoral head sits in the deep acetabulum.',
      plain: 'Most movable joints are synovial joints, and they come in six types classified by the shape of the meeting surfaces and how many axes (directions) of movement they allow: hinge moves in one plane, pivot rotates about one axis, condylar moves in two planes, saddle also moves in two planes plus opposition, plane glides, and ball-and-socket moves in all three. Each type comes with examples — the memorisation target.',
      keyFacts: [
        'Hinge — one plane. Elbow; interphalangeal joints.',
        'Pivot — rotation about one axis. Median atlanto-axial joint; proximal radioulnar joint.',
        'Condylar — two planes. Radiocarpal (wrist); metacarpophalangeal joints.',
        'Saddle — two planes plus opposition. Carpo-metacarpal joint of the thumb.',
        'Plane — gliding. Apophyseal (facet) joints; acromioclavicular joint.',
        'Ball-and-socket — all three planes. Glenohumeral; hip.',
        'Monoaxial means movement in one plane only.',
      ],
      prerequisites: ['hss2011-joints-classification'],
      examples: [],
    },
    memory: {
      chunking: 'Sort by how many planes first, then name the shape. One plane: hinge and pivot. Two planes: condylar and saddle. Three planes: ball-and-socket. Gliding sits outside the count.',
      comparison: 'Glenohumeral and hip are both ball-and-socket, and both let you move in three planes — but the glenoid fossa is shallow and the acetabulum is deep. Same class, opposite trade-off between mobility and stability.',
      visualCue: 'A saddle joint really is a saddle: two surfaces each curved one way and hollow the other, sitting across each other. That is why the thumb can oppose and the wrist cannot.',
      mnemonic: 'The thumb is the saddle. If a question mentions opposition, it is the carpo-metacarpal joint of the thumb every time.',
    },
    practice: [
      { type: 'matching', prompt: 'Match each synovial joint type to its example.',
        pairs: [['Hinge', 'Elbow joint'], ['Pivot', 'Median atlanto-axial joint'], ['Saddle', 'Carpo-metacarpal joint of the thumb'], ['Ball-and-socket', 'Glenohumeral joint']],
        explanation: 'These are the worked examples used across the Module 0 and Module 4 material.' },
      { type: 'mcq', prompt: 'Which joint type allows movement in all three planes?', options: ['Hinge', 'Pivot', 'Plane', 'Ball-and-socket'], answer: 3,
        explanation: 'Ball-and-socket is the triaxial type — the glenohumeral and hip joints. A hinge is monoaxial, moving in one plane only.' },
      { type: 'comparison', prompt: 'Both the glenohumeral and hip joints are ball-and-socket. What is the anatomical difference that changes their behaviour?',
        options: [
          'The glenoid fossa is shallow while the acetabulum is deep, so the shoulder trades stability for mobility',
          'The hip has no articular cartilage',
          'The shoulder is a fibrous joint',
          'The hip allows movement in only two planes',
        ], answer: 0,
        explanation: 'Both are ball-and-socket and both are triaxial. The difference is socket depth: the shallow glenoid fossa allows a much wider range but far less bony stability than the deep acetabulum.' },
      { type: 'typed', prompt: 'Which synovial joint type carries supination and pronation of the forearm?', accept: ['pivot', 'pivot joint'],
        explanation: 'A pivot joint — the radioulnar joints, where the radius rotates against the ulna.' },
      { type: 'sequence', prompt: 'Order these synovial joint types by how many planes of movement they allow, fewest first.', items: ['Hinge — one plane', 'Condylar — two planes', 'Ball-and-socket — three planes'],
        explanation: 'Monoaxial hinge, then biaxial condylar, then triaxial ball-and-socket.' },
    ],
    application: [
      { type: 'scenario', prompt: 'A joint allows you to flex, extend, abduct, adduct and oppose. Which type is it, where is it, and which single movement rules out the alternatives?',
        model: 'A saddle joint — the carpo-metacarpal joint of the thumb. Opposition is the deciding movement: a condylar joint gives you two planes but cannot oppose, and only the thumb’s saddle joint carries opposition among the types listed.',
        rubric: ['Names saddle', 'Locates it at the thumb CMC joint', 'Uses opposition as the discriminator'] },
    ],
    commonMistakes: [
      'Calling the wrist a hinge. It is condylar — it abducts and adducts as well as flexing and extending.',
      'Forgetting that both the elbow and the proximal radioulnar joint sit at the elbow region but are different joint types doing different jobs.',
    ],
    skills: [
      'Plane count, not appearance, is the classification axis — and it is what exposes the wrist: it flexes AND abducts and adducts, so it is condylar (two planes), however hinge-like it looks. One plane: hinge and pivot. Two: condylar and saddle. Three: ball-and-socket.',
      'Two ball-and-socket joints are not two copies of one joint: the shallow glenoid fossa buys the shoulder range at the price of stability, the deep acetabulum buys the hip stability at the price of range. Same class, opposite trade-off — socket depth is the whole comparison.',
      'Opposition belongs to exactly one type — the thumb\'s saddle carpo-metacarpal joint — and one location can hold two types: at the elbow region a hinge and the proximal radioulnar pivot sit side by side doing different jobs, so where a joint sits never tells you what type it is.',
    ],
    selfCheck: 'From a blank page: all six types each with its example, why the wrist is condylar and not hinge, and the flex-extend-abduct-adduct-oppose scenario solved by naming the deciding movement.',
    sourceRefs: [{ ref: 'hss.4.1', location: 'Slides "Classification of Joints — Synovial joints", "Synovial joints"' }, { ref: 'hss.m0.1718', location: 'L1 p18 joint types; p29 atlanto-axial; p43–51 elbow, radioulnar, wrist and thumb movements' }, { ref: 'hss.1516.lec11', location: 'Skeletal, joint and muscular system lecture' }],
  },
  {
    id: 'abct2326-cvs-conduction',
    subject: 'ABCT2326', unit: 'phys.cvs', type: 'sequence',
    title: 'The cardiac conducting system',
    tags: ['cardiovascular', 'high-yield'],
    priorKnowledge: {
      level: 'dse-bio', covers: 'part', dsePart: 'elective-hp',
      syllabusRef: { ref: 'edb.bio', location: 'Elective V(c) "Regulation of gas content in blood" — "Control of cardiac output: heart rate and stroke volume, Pacemaker and cardiac cycle". The elective names the pacemaker; it does not go inside it.' },
      beyond: [
        { t: 'The route as five named stops: SA node → AV node → AV bundle (bundle of His) → left and right bundle branches → Purkinje fibres.',
          src: { ref: 'phys.2', location: 'Slides 43–52 "The Conducting System"' } },
        { t: 'Inside the pacemaker: the prepotential drifting from about −60 mV to a −40 mV threshold on Na⁺ through an HCN channel, then voltage-gated Ca²⁺ channels for the upstroke.',
          src: { ref: 'phys.2', location: 'Slides 47–48 "Pacemaker potential"' } },
        { t: 'Why a special route exists at all — the fibrous cardiac skeleton does not conduct, so the impulse cannot simply spread from atria to ventricles.',
          src: { ref: 'phys.2', location: 'Slide 49 "From SA node to AV node"' } },
        { t: 'The AV node as a deliberate delay rather than a relay, which is what lets the atria finish emptying first.',
          src: { ref: 'phys.2', location: 'Slide 50 "The Conducting System – AV Node"' } },
        { t: 'Myocardial cells resting at −90 mV with a 200–300 ms plateau from balanced Ca²⁺ influx and K⁺ efflux.',
          src: { ref: 'phys.2', location: 'Slide 53 "Myocardial Action Potentials"' } },
      ],
    },
    lesson: {
      explanation: 'The heart holds two types of cardiac muscle cell: the conducting system, which initiates and distributes the electrical impulses that stimulate contraction and so controls and coordinates the heartbeat, and the contractile cells, which produce the contractions that propel blood. The cardiac cycle begins with an action potential at the sinoatrial node, which is transmitted through the conducting system and produces action potentials in the contractile cells. The SA node sits in the posterior wall of the right atrium, contains pacemaker cells and begins atrial activation. Its prepotential, or pacemaker potential, drifts spontaneously from about −60 mV toward a −40 mV threshold — the drift is caused by Na⁺ flowing through an HCN channel that opens when the cell is hyperpolarised — and at threshold voltage-gated Ca²⁺ channels open to produce the upstroke. Because the SA node depolarises first, it sets the heart rate. The impulse spreads through the atrial myocardium via gap junctions, but needs a special route to the ventricles because the fibrous cardiac skeleton does not conduct. It reaches the AV node in the floor of the right atrium, which delays it while atrial contraction begins, then passes to the AV bundle (bundle of His) in the septum, out to the left and right bundle branches, and finally to the Purkinje fibres, which distribute it through the ventricles so ventricular contraction begins.',
      keyFacts: [
        'Two cell types: conducting system (initiates and distributes) and contractile cells (propel blood).',
        'SA node — posterior wall of right atrium, holds pacemaker cells, sets heart rate.',
        'Pacemaker potential drifts from about −60 mV to a −40 mV threshold via an HCN Na⁺ channel; Ca²⁺ channels then open for the upstroke.',
        'AV node — floor of the right atrium; receives, then delays the impulse.',
        'AV bundle (bundle of His) in the septum → left and right bundle branches → Purkinje fibres.',
        'The moderator band conducts to the papillary muscles.',
        'The fibrous cardiac skeleton is why a special conducting route to the ventricles is needed at all.',
        'Myocardial cells rest at −90 mV and have a 200–300 ms plateau from balanced Ca²⁺ influx and K⁺ efflux.',
      ],
      prerequisites: ['abct2326-cvs-heart-structure'],
      examples: [],
    },
    memory: {
      sequence: 'SA → AV → bundle of His → bundle branches → Purkinje. Five stops, top to bottom, right to left. Say it as a route, not a list.',
      location: 'Both nodes are in the right atrium — SA in the posterior wall, AV in the floor. If you can remember they are neighbours, you only have to remember which is higher.',
      chunking: 'The AV node’s job is a pause, not a relay. That delay is what lets the atria finish emptying before the ventricles squeeze.',
      wordOrigin: 'Sino-atrial names its location: the sinus of the atrium. Atrio-ventricular names the border it sits on.',
    },
    practice: [
      { type: 'sequence', prompt: 'Order the structures of the conducting system as the impulse travels.',
        items: ['Sinoatrial (SA) node', 'Internodal pathways / atrial myocardium', 'Atrioventricular (AV) node', 'AV bundle (bundle of His)', 'Left and right bundle branches', 'Purkinje fibres'],
        explanation: 'This is the five-step route given across the conducting-system slides, from atrial activation to ventricular contraction.' },
      { type: 'typed', prompt: 'Where in the heart is the SA node located?', accept: ['posterior wall of the right atrium', 'right atrium', 'posterior wall of right atrium', 'wall of the right atrium'],
        explanation: 'The posterior wall of the right atrium. The AV node is lower, in the floor of the same chamber.' },
      { type: 'mcq', prompt: 'What is the functional point of the delay at the AV node?', options: ['To slow the overall heart rate', 'To let atrial contraction complete before the ventricles contract', 'To protect the Purkinje fibres', 'To recharge the SA node'], answer: 1,
        explanation: 'The AV node delays the impulse while atrial contraction begins, so the atria finish emptying into the ventricles before ventricular contraction starts.' },
      { type: 'cloze', prompt: 'The SA node sets the heart rate because its ______ depolarises spontaneously and reaches threshold first.', accept: ['prepotential', 'pacemaker potential', 'prepotential (pacemaker potential)'],
        explanation: 'The prepotential, also called the pacemaker potential — the resting potential of conducting cells, which drifts toward threshold on its own.' },
      { type: 'explain', prompt: 'Why does the impulse need the AV node and bundle of His at all, rather than simply spreading from atria to ventricles?',
        model: 'Because the fibrous cardiac skeleton between the atria and ventricles does not conduct. Atrial impulses spread through the atrial myocardium via gap junctions but cannot cross that insulating layer, so the AV node and AV bundle provide the only electrical route through to the ventricles.',
        rubric: ['Names the fibrous cardiac skeleton as non-conducting', 'States it separates atria from ventricles electrically', 'Identifies the AV node/bundle as the only route through'] },
    ],
    application: [
      { type: 'scenario', prompt: 'If the SA node stopped firing but the AV node kept working, what would happen to the heart rate, and why does any beat survive at all?',
        model: 'A beat survives because pacemaker cells are not unique to the SA node — the conducting system as a whole has cells whose prepotential depolarises spontaneously. The SA node normally sets the rate only because it reaches threshold first. With it silent, a slower downstream pacemaker takes over, so the heart keeps beating but more slowly.',
        rubric: ['States the SA node leads because it depolarises fastest', 'Recognises other conducting cells also have a prepotential', 'Predicts a slower rate rather than arrest'] },
    ],
    commonMistakes: [
      'Treating the AV node as a simple relay — its defining contribution is the delay.',
      'Placing the bundle of His in the atria; it is in the interventricular septum.',
    ],
    skills: [
      'The conducting system exists because of a wall, not for speed: the fibrous cardiac skeleton does not conduct, so atrial impulses spreading through gap junctions stop dead at it — the AV node and AV bundle are the only electrical route into the ventricles, which is also why the bundle of His sits in the interventricular septum, not the atria.',
      'The AV node\'s defining contribution is the pause, not the relay: it delays the impulse so the atria finish emptying before the ventricles squeeze. Both nodes are neighbours in the right atrium — SA in the posterior wall, AV in the floor — so the delay is built into the architecture, not bolted on.',
      'The SA node is the leader, not the only pacemaker: every conducting cell carries a spontaneous prepotential, and the SA node sets the rate only because its drift (−60 mV toward the −40 mV threshold on Na⁺ through an HCN channel, then voltage-gated Ca²⁺ for the upstroke) gets there first. SA failure means a slower downstream pacemaker takes over — a slower beat, not arrest.',
    ],
    selfCheck: 'From a blank page: the full route with locations, why the fibrous cardiac skeleton forces this route to exist, what the AV node’s delay buys, and the SA-node-fails prediction — a slower beat, not arrest.',
    sourceRefs: [{ ref: 'phys.2', location: 'Slides 40–53 the conducting system, SA node, pacemaker potential, AV node, AV bundle, Purkinje fibres, myocardial action potentials' }],
  },
  {
    id: 'abct2326-cvs-ecg-cycle',
    subject: 'ABCT2326', unit: 'phys.cvs', type: 'definition',
    title: 'ECG waves, the cardiac cycle and heart sounds',
    tags: ['cardiovascular', 'high-yield'],
    priorKnowledge: {
      level: 'dse-bio', covers: 'part', dsePart: 'elective-hp',
      syllabusRef: { ref: 'edb.bio', location: 'Elective V(c) — "Outline the major events during the cardiac cycle" and cardiac output as heart rate × stroke volume. The ECG trace itself is not in the syllabus at all.' },
      beyond: [
        { t: 'The ECG as three named features — P wave atrial depolarisation, QRS ventricular depolarisation, T wave ventricular repolarisation — plus the P–R and Q–T intervals.',
          src: { ref: 'phys.2', location: 'Slides 57–59 "Electrocardiogram (ECG or EKG)"' } },
        { t: 'Three volumes that subtract: end-diastolic volume minus stroke volume leaves end-systolic volume.',
          src: { ref: 'phys.2', location: 'Slides 60–62 "Cardiac Cycle"' } },
        { t: 'The Frank–Starling law — stroke volume rises with end-diastolic volume because the stretch increases the force of contraction.',
          src: { ref: 'phys.2', location: 'Slides 62–63 "Cardiac Cycle continued"' } },
        { t: 'S1 from the AV valves and S2 from the semilunar valves, so the two sounds are doors closing in order.',
          src: { ref: 'phys.2', location: 'Slide 64 "Heart Sounds"' } },
        { t: 'A ventricular action potential of 250–300 ms — about thirty times a skeletal muscle fibre — whose long refractory period is what prevents summation and tetany in the heart.',
          src: { ref: 'phys.2', location: 'Slide 55 "Refractory Periods"' } },
      ],
    },
    lesson: {
      explanation: 'An electrocardiogram is a recording of the electrical events in the heart, obtained by electrodes at specific body locations, and abnormal patterns are used to diagnose damage. It has three features: the P wave, atrial depolarisation; the QRS complex, ventricular depolarisation; and the T wave, ventricular repolarisation. The P–R interval runs from the start of atrial depolarisation to the start of the QRS complex, and the Q–T interval from ventricular depolarisation to ventricular repolarisation. The cardiac cycle itself is the repeating pattern of contraction and relaxation: systole is the contraction phase, diastole the relaxation phase, and both atria contract simultaneously with the ventricles following 0.1–0.2 seconds later. End-diastolic volume is the blood in the ventricles at the end of diastole, stroke volume is the amount ejected during systole, and end-systolic volume is what is left afterwards. The Frank–Starling law states that stroke volume increases as end-diastolic volume increases, because the increased blood volume stretches the ventricular wall and the force of contraction rises. Two loud heart sounds mark the cycle: S1 is produced by the AV valves and S2 by the semilunar valves. Cardiac muscle also has a long absolute refractory period — the ventricular action potential lasts 250–300 ms, about thirty times longer than a skeletal muscle fibre — which prevents summation and tetany.',
      plain: 'An ECG is a trace of the heart’s electrical activity, read as three waves: P (the atria squeezing), QRS (the ventricles squeezing) and T (the ventricles relaxing). The cardiac cycle is the repeating squeeze-and-relax pattern — systole squeezes, diastole relaxes. The Frank–Starling law says more blood in the ventricle before a beat makes the next squeeze stronger. Two heart sounds mark the cycle: S1 from the AV valves and S2 from the semilunar valves.',
      keyFacts: [
        'P wave — atria depolarise. QRS complex — ventricles depolarise. T wave — ventricles repolarise.',
        'P–R interval: start of atrial depolarisation to start of QRS. Q–T interval: ventricular depolarisation to repolarisation.',
        'Systole = contraction; diastole = relaxation. Ventricles follow the atria by 0.1–0.2 s.',
        'End-diastolic volume → stroke volume ejected → end-systolic volume left behind.',
        'Frank–Starling law: stroke volume rises as end-diastolic volume rises, because stretch increases force of contraction.',
        'S1 is produced by the AV valves; S2 by the semilunar valves.',
        'Ventricular action potential lasts 250–300 ms — about 30× a skeletal muscle fibre — and the long refractory period prevents summation and tetany.',
      ],
      prerequisites: ['abct2326-cvs-conduction'],
      examples: [],
    },
    memory: {
      mnemonic: 'P before QRS before T, in the order the heart actually fires: atria depolarise, ventricles depolarise, ventricles recover. There is no wave for atrial repolarisation because the QRS buries it.',
      chunking: 'Three volumes, one subtraction: end-diastolic minus stroke volume equals end-systolic. If you know two you can derive the third.',
      visualCue: 'S1 "lubb" is the AV valves shutting as the ventricles start to squeeze; S2 "dupp" is the semilunar valves shutting as they finish. The sounds are doors closing, in order.',
      comparison: 'Systole and diastole are easy to swap under pressure. SyStole = Squeeze.',
    },
    practice: [
      { type: 'matching', prompt: 'Match each ECG feature to the electrical event it represents.',
        pairs: [['P wave', 'Atria depolarise'], ['QRS complex', 'Ventricles depolarise'], ['T wave', 'Ventricles repolarise'], ['P–R interval', 'Start of atrial depolarisation to start of QRS']],
        explanation: 'These are the ECG features listed on the electrocardiogram slide.' },
      { type: 'mcq', prompt: 'Which valves produce the first heart sound, S1?', options: ['The semilunar valves', 'The AV valves', 'The aortic valve alone', 'The pulmonary valve alone'], answer: 1,
        explanation: 'S1 is produced by the AV valves and S2 by the semilunar valves.' },
      { type: 'typed', prompt: 'What is the name of the law stating that stroke volume increases as end-diastolic volume increases?', accept: ['frank-starling', 'frank starling', 'frank-starling law', 'starling'],
        explanation: 'The Frank–Starling law. Increased blood volume stretches the ventricular wall, and the force of contraction rises.' },
      { type: 'cloze', prompt: 'The contraction phase of the cardiac cycle is called ______ and the relaxation phase ______.', accept: ['systole; diastole', 'systole, diastole', 'systole and diastole'],
        explanation: 'Systole is contraction, diastole is relaxation.' },
      { type: 'explain', prompt: 'Why does the long refractory period of cardiac muscle matter?',
        model: 'The ventricular action potential lasts 250–300 ms, roughly thirty times a skeletal muscle fibre. That long absolute refractory period means the cell cannot respond to a second stimulus during it, so cardiac muscle cannot summate or go into tetany — it has to relax and refill between beats.',
        rubric: ['Gives the 250–300 ms duration or the 30× comparison', 'States it prevents summation and tetany', 'Connects that to the need to refill'] },
    ],
    application: [
      { type: 'scenario', prompt: 'A patient’s end-diastolic volume rises after a fluid infusion. Using the Frank–Starling law, predict what happens to stroke volume and say why.',
        model: 'Stroke volume increases. The extra blood volume stretches the ventricular wall further at the end of diastole, and the force of contraction rises with that stretch, so more blood is ejected during systole.',
        rubric: ['Predicts an increase in stroke volume', 'Names ventricular wall stretch as the mechanism', 'Links stretch to force of contraction'] },
    ],
    commonMistakes: [
      'Looking for a wave representing atrial repolarisation — the lecture lists only P, QRS and T.',
      'Swapping S1 and S2. S1 is the AV valves, at the start of ventricular contraction.',
    ],
    skills: [
      'The missing wave is the lesson, not an omission: atrial repolarisation happens, but the QRS complex buries it — which is why the ECG carries exactly three features, and why "find the wave for atrial repolarisation" is the trap the lecture pre-empts.',
      'The heart sounds are two valves closing in order, not one valve clapping twice: S1 is the AV valves shutting as ventricular systole begins, S2 the semilunar valves as it ends — and swapping them silently reverses the timeline of the whole cycle.',
      'The refractory period is why the heart cannot be tetanised: a ventricular action potential lasts 250–300 ms, about thirty times a skeletal muscle fibre, so no second stimulus can summate within it — the cycle must finish and the ventricle must refill. The Frank–Starling law rides on the same geometry: more end-diastolic filling means more wall stretch, more force, and EDV − SV = ESV is the subtraction that holds it.',
    ],
    selfCheck: 'From a blank page: the labelled cycle sketch, the Frank–Starling infusion prediction with the stretch mechanism, and the 250–300 ms refractory-period consequence — no summation, no tetany, the heart must refill.',
    sourceRefs: [{ ref: 'phys.2', location: 'Slides 55–64 refractory periods, electrocardiogram, cardiac cycle, heart sounds; Figure 20-18b' }],
  },
  {
    id: 'abct2326-resp-gas-transport',
    subject: 'ABCT2326', unit: 'phys.resp', type: 'definition',
    title: 'Gas exchange, oxygen transport and the control of respiration',
    tags: ['respiratory', 'high-yield'],
    priorKnowledge: {
      level: 'dse-bio', covers: 'part', dsePart: 'elective-hp',
      syllabusRef: { ref: 'edb.bio', location: 'Elective V(c) "Regulation of gas content in blood" — control of the rate and depth of breathing, the respiratory centre and chemoreceptors, and the effect of blood CO₂. Alveolar histology is not in the syllabus.' },
      beyond: [
        { t: 'Alveolar histology: simple squamous epithelium of thin type I pneumocytes where most exchange happens, type II pneumocytes (septal cells) making surfactant, alveolar macrophages as dust cells.',
          src: { ref: 'phys.3', location: 'Slide 10 "Alveolar epithelium"' } },
        { t: 'What surfactant is for — an oily phospholipid and protein secretion that lowers surface tension and stops the lung collapsing.',
          src: { ref: 'phys.3', location: 'Slide 13 "Surfactant"' } },
        { t: 'The oxygen–haemoglobin saturation curve shifted by pH (normal blood 7.35–7.45) and by temperature (normal 38 °C).',
          src: { ref: 'phys.3', location: 'Slides 47–54 "Oxygen–hemoglobin saturation curve", "Hemoglobin and pH", "Hemoglobin and temperature"' } },
        { t: 'Carbon dioxide carried three ways: converted to carbonic acid, bound to haemoglobin inside red cells, dissolved in plasma.',
          src: { ref: 'phys.3', location: 'Slide 55 "Carbon dioxide gas transport"' } },
        { t: 'The respiratory centre resolved into parts — dorsal and ventral respiratory groups in the medulla, modified by the apneustic and pneumotaxic centres of the pons.',
          src: { ref: 'phys.3', location: 'Slides 59–64 "The respiratory centers of the brain"' } },
        { t: 'Chemoreceptor reflexes routed by named nerves — glossopharyngeal (N IX) from the carotid bodies, vagus (N X) from the aortic bodies — with central chemoreceptors on the ventrolateral medulla reading CSF.',
          src: { ref: 'phys.3', location: 'Slides 68–71 "Chemoreceptor reflexes"' } },
      ],
    },
    lesson: {
      explanation: 'Gas exchange happens across the alveolar epithelium, which is simple squamous epithelium made of thin type I pneumocytes patrolled by alveolar macrophages, or dust cells, alongside type II pneumocytes that produce surfactant. The majority of gas exchange occurs across the type I pneumocytes, and a single capillary may exchange with several alveoli at once. Gases move down partial-pressure gradients between alveolar air and the alveolar capillaries. Oxygen binds to the iron ions in haemoglobin molecules to form oxyhaemoglobin; haemoglobin saturation is the percentage of heme units carrying bound oxygen, and the oxygen–haemoglobin saturation curve relates that saturation to the partial pressure of oxygen. Respiration is controlled by respiratory centres whose ventral and dorsal respiratory groups establish the basic pace and depth, modified by the pneumotaxic centre. Reflex input comes from chemoreceptors sensitive to PCO₂, PO₂ or pH of blood or cerebrospinal fluid; baroreceptors in the aortic or carotid sinuses sensitive to blood pressure; stretch receptors responding to lung volume; and irritant, pain, temperature and visceral sensations. Peripheral chemoreceptor input arrives by the glossopharyngeal nerve from the carotid bodies and the vagus nerve from the aortic bodies, while central chemoreceptors on the ventrolateral surface of the medulla oblongata respond to the PCO₂ and pH of cerebrospinal fluid. Chemoreceptor stimulation increases the depth and rate of respiration, and is subject to adaptation — sensitivity falls under chronic stimulation.',
      plain: 'Gas exchange happens across the very thin walls of the alveoli (the air sacs), where oxygen binds to iron in haemoglobin to make oxyhaemoglobin; how much oxygen is carried depends on its partial pressure — that relationship is the saturation curve. Breathing itself is set by respiratory centres in the brain and tuned by reflex inputs: chemoreceptors that sense carbon dioxide, oxygen or pH, baroreceptors that sense blood pressure, stretch receptors that sense lung volume, and others.',
      keyFacts: [
        'Type I pneumocytes — thin, where the majority of gas exchange occurs. Type II pneumocytes — produce surfactant. Alveolar macrophages — dust cells.',
        'Oxygen binds the iron ions of haemoglobin to form oxyhaemoglobin.',
        'Haemoglobin saturation = the percentage of heme units carrying bound oxygen.',
        'Respiratory centres: ventral and dorsal respiratory groups set pace and depth; the pneumotaxic centre modifies the pace.',
        'Chemoreceptors respond to PCO₂, PO₂ or pH of blood or CSF.',
        'Glossopharyngeal nerve (CN IX) from the carotid bodies; vagus nerve (CN X) from the aortic bodies.',
        'Central chemoreceptors sit on the ventrolateral surface of the medulla oblongata and monitor CSF.',
        'Chemoreceptor stimulation raises depth and rate, and adapts under chronic stimulation.',
      ],
      prerequisites: ['abct2326-resp-pathway'],
      examples: [],
    },
    memory: {
      comparison: 'Type I is thin so gas crosses it; type II is secretory so it makes surfactant. One roman numeral, one job: I for interchange, II for the substance.',
      location: 'Two peripheral sensing sites, two nerves, and each nerve serves the body part it is named near: glossopharyngeal from the carotid bodies in the neck, vagus from the aortic bodies in the chest.',
      chunking: 'Control has three layers: a rhythm generator (VRG/DRG), a modifier (pneumotaxic centre), and sensors feeding back (chemo-, baro-, stretch).',
      wordOrigin: 'Oxyhaemoglobin is simply oxygen + haem + globin — the carrier named after what it is carrying.',
    },
    practice: [
      { type: 'mcq', prompt: 'Across which cell type does the majority of gas exchange occur?', options: ['Type II pneumocytes', 'Alveolar macrophages', 'Type I pneumocytes', 'Goblet cells'], answer: 2,
        explanation: 'Type I pneumocytes are the thin, delicate cells of the alveolar epithelium and the majority of gas exchange occurs across them. Type II pneumocytes make surfactant.' },
      { type: 'typed', prompt: 'Oxygen binds to which part of the haemoglobin molecule?', accept: ['iron ions', 'iron', 'the iron ions', 'heme iron'],
        explanation: 'The iron ions in haemoglobin. The result is called oxyhaemoglobin.' },
      { type: 'matching', prompt: 'Match each receptor site to the nerve carrying its input.',
        pairs: [['Carotid bodies', 'Glossopharyngeal nerve (CN IX)'], ['Aortic bodies', 'Vagus nerve (CN X)'], ['Cerebrospinal fluid', 'Central chemoreceptors on the medulla oblongata'], ['Aortic and carotid sinuses', 'Baroreceptors sensitive to blood pressure']],
        explanation: 'These are the chemoreceptor and baroreceptor routes given in the control-of-respiration slides.' },
      { type: 'cloze', prompt: 'Haemoglobin ______ is the percentage of heme units in a haemoglobin molecule that contain bound oxygen.', accept: ['saturation'],
        explanation: 'Saturation. The oxygen–haemoglobin saturation curve plots it against the partial pressure of oxygen.' },
      { type: 'explain', prompt: 'What does it mean that chemoreceptor stimulation "is subject to adaptation"?',
        model: 'Sensitivity falls under chronic stimulation. A chemoreceptor that is being stimulated continuously stops driving the same increase in depth and rate that the same signal would produce acutely, so a long-standing abnormality provokes less of a response than a sudden one.',
        rubric: ['States sensitivity decreases with chronic stimulation', 'Contrasts acute with chronic response'] },
    ],
    application: [
      { type: 'scenario', prompt: 'Your respiratory rate rises sharply during exercise. Name two different receptor types from this lecture that could be contributing, and say what each is responding to.',
        model: 'Chemoreceptors responding to rising PCO₂, falling PO₂ or falling pH in blood or cerebrospinal fluid; and stretch receptors responding to the changes in lung volume as breathing deepens. Baroreceptors in the aortic and carotid sinuses could also contribute, since they respond to the blood-pressure changes exercise produces.',
        rubric: ['Names at least two receptor types from the lecture list', 'States correctly what each responds to'] },
    ],
    commonMistakes: [
      'Attributing surfactant production to type I pneumocytes — that is type II.',
      'Assuming central chemoreceptors sense blood; they monitor cerebrospinal fluid.',
    ],
    skills: [
      'The roman numerals are job descriptions, not a numbering: type I is the thin wall that interchange crosses, type II is the secretory cell that makes surfactant — attributing surfactant to type I is the named mistake — and the dust cells (alveolar macrophages) are the third resident of the alveolus, carrying no numeral at all.',
      '"Chemoreceptor" splits on which fluid is read: the peripheral carotid bodies (via the glossopharyngeal nerve, CN IX) and aortic bodies (via the vagus, CN X) sample blood, while the central chemoreceptors on the ventrolateral medulla monitor cerebrospinal fluid — assuming the central ones read blood is the named mistake.',
      'Control is layered, and the layers do different jobs: the ventral and dorsal respiratory groups generate rhythm and depth, the pneumotaxic centre modifies pace, and the sensors — chemo-, baro-, stretch — feed back. The sensors themselves adapt: chronic stimulation lowers sensitivity, so a long-standing abnormality provokes less response than a sudden one.',
    ],
    selfCheck: 'From a blank page: the three alveolar cell types with their jobs, both chemoreceptor-to-nerve pairs plus the central route, and the exercise scenario naming two receptor types with what each responds to.',
    sourceRefs: [{ ref: 'phys.3', location: 'Slides 10–12 alveolar epithelium; 66–74 control of respiration, respiratory and chemoreceptor reflexes, homeostasis of arterial PCO₂; partial pressure and oxygen–haemoglobin saturation slides' }],
  },
  {
    id: 'abct2326-immune-adaptive',
    subject: 'ABCT2326', unit: 'phys.imm', type: 'comparison',
    title: 'Inflammation, complement and adaptive immunity',
    tags: ['immune', 'high-yield'],
    priorKnowledge: {
      level: 'dse-bio', covers: 'part', dsePart: 'core',
      syllabusRef: { ref: 'edb.bio', location: 'Compulsory IV(c) "Body defence mechanisms" — specific defence: immune response, antigen and antibody, B and T lymphocytes, primary and secondary responses, active and passive immunity. Complement and MHC are not in it.' },
      beyond: [
        { t: 'The complement cascade with its steps named: about 30 plasma proteins, classical or alternative activation, then the common pathway where C3b splits C5 and C5b–C9 assemble the membrane attack complex.',
          src: { ref: 'phys.10', location: 'Slides 27, 29 "Complement System"' } },
        { t: 'Inflammation as a named set: four Latin signs, three effects, and the products necrosis, pus and abscess.',
          src: { ref: 'phys.10', location: 'Slides 31–33 "Inflammation"' } },
        { t: 'Active and passive immunity each split again into naturally acquired and artificially induced — a four-cell grid, where DSE stops at the pair.',
          src: { ref: 'phys.10', location: 'Slide 35 "Active Immunity / Passive Immunity"' } },
        { t: 'Four major T cell types: cytotoxic, memory, helper and suppressor.',
          src: { ref: 'phys.10', location: 'Slide 39 "4 Major Types of T Cells"' } },
        { t: 'MHC proteins, coded on chromosome 6, as the reason T cells only ever see presented antigen — class I on all nucleated cells, class II on antigen-presenting cells.',
          src: { ref: 'phys.10', location: 'Slides 40–41 "T Cells and Immunity", "Two Classes of MHC Proteins"' } },
      ],
    },
    lesson: {
      explanation: 'Inflammation is a localised response triggered by any stimulus that kills cells or injures tissue. Its four principal signs carry Latin names: swelling (tumor), redness (rubor), heat (calor) and pain (dolor). It has three effects — temporary repair and a barrier against pathogens, retarding the spread of pathogens into surrounding areas, and mobilising local and systemic defences while facilitating repair. Its products include necrosis, the destruction of injured cells; pus, the viscous mixture of debris, fluid and dead cells that accumulates at the injury site; and an abscess, an accumulation of pus in an enclosed tissue space. Complement is a system of about thirty plasma proteins that work in cascades. There are two activation pathways: the classical pathway, which requires antibody binding and C1 attachment and is the most rapid and effective, and the alternative pathway, which involves no antibody, occurs more slowly and less effectively, and is activated by exposure to foreign materials. Either pathway turns on the common pathway from C5 to C9, generating the membrane attack complex on the bacterial surface and causing cell lysis. Adaptive immunity is not present at birth: you acquire immunity to a specific antigen only after exposure to it or by receiving antibodies. It splits into active immunity, where antibodies develop after exposure to an antigen, and passive immunity, where antibodies are transferred from another source; and it is studied as cell-mediated (cellular) immunity versus antibody-mediated (humoral) immunity, involving T cells and B cells respectively.',
      plain: 'Inflammation is the body’s local reaction to injury, with four classic signs — swelling, redness, heat, pain (tumor, rubor, calor, dolor in the exam wording). Complement is a team of about thirty plasma proteins that work in cascades; the classical pathway needs antibodies and is fast, the alternative pathway does not and is slower. Adaptive immunity is learned after birth: active when your own body makes antibodies after exposure, passive when you receive them from outside.',
      keyFacts: [
        'Four signs of inflammation: swelling (tumor), redness (rubor), heat (calor), pain (dolor).',
        'Three effects: temporary repair and barrier, retarding spread, mobilising defences and facilitating repair.',
        'Products: necrosis, pus, abscess.',
        'Complement = about 30 plasma proteins working in a cascade.',
        'Classical pathway needs antibody binding and C1; it is the most rapid and effective. Alternative pathway needs no antibody, is slower and less effective.',
        'Both converge on the common pathway C5–C9, forming the membrane attack complex (MAC) and lysing the cell.',
        'Adaptive immunity is acquired after birth — by exposure to an antigen or by receiving antibodies.',
        'Active immunity: antibodies develop after exposure. Passive immunity: antibodies transferred from another source.',
        'Cell-mediated immunity involves T cells; antibody-mediated (humoral) immunity involves B cells.',
      ],
      prerequisites: ['abct2326-innate-adaptive'],
      examples: [],
    },
    memory: {
      firstLetter: 'The four Latin signs are easier as a set than singly: tumor, rubor, calor, dolor — swelling, redness, heat, pain. They rhyme, which is the point.',
      comparison: 'Classical vs alternative complement: classical needs an antibody and is fast; alternative needs none and is slow. The pathway that waits for a specific antibody is the one that works best once it arrives.',
      chunking: 'Active vs passive immunity is about who made the antibody. Active — you did, after exposure. Passive — someone else did, and it was transferred.',
      mnemonic: 'B cells make antiBodies. T cells do the cell-mediated work. One letter each, and it holds.',
    },
    practice: [
      { type: 'matching', prompt: 'Match each Latin sign of inflammation to its meaning.',
        pairs: [['Tumor', 'Swelling'], ['Rubor', 'Redness'], ['Calor', 'Heat'], ['Dolor', 'Pain']],
        explanation: 'These are the four principal signs and symptoms of inflammation as given in the lecture, with their Latin names.' },
      { type: 'comparison', prompt: 'What distinguishes the classical from the alternative complement pathway?',
        options: [
          'The classical pathway requires antibody binding and is faster and more effective; the alternative requires no antibody and is slower',
          'The classical pathway is slower and requires no antibody',
          'Only the alternative pathway forms a membrane attack complex',
          'They use entirely separate proteins with no common pathway',
        ], answer: 0,
        explanation: 'The classical pathway begins with antibody binding and C1 attachment and is the most rapid and effective. The alternative involves no antibody, is slower and less effective. Both converge on the common pathway C5–C9 and both end in the membrane attack complex.' },
      { type: 'typed', prompt: 'What is the name of the structure generated by the common complement pathway that lyses the target cell?', accept: ['membrane attack complex', 'mac', 'membrane attack complex (mac)'],
        explanation: 'The membrane attack complex (MAC), formed from C5b with C6, C7, C8 and C9.' },
      { type: 'mcq', prompt: 'Antibodies transferred from another source rather than made after your own exposure describes:', options: ['Active immunity', 'Passive immunity', 'Innate immunity', 'Cell-mediated immunity'], answer: 1,
        explanation: 'Passive immunity — antibodies are transferred from another source. Active immunity is where antibodies develop after your own exposure to the antigen.' },
      { type: 'cloze', prompt: 'Cell-mediated immunity involves ______ cells, while antibody-mediated (humoral) immunity involves ______ cells.', accept: ['t; b', 't, b', 't cells and b cells', 't and b'],
        explanation: 'T cells for cell-mediated, B cells for antibody-mediated (humoral) immunity.' },
    ],
    application: [
      { type: 'scenario', prompt: 'An accumulation of pus has formed in an enclosed tissue space. Name it, and trace it back through the inflammatory process that produced it.',
        model: 'That is an abscess. Inflammation was triggered by a stimulus that killed cells or injured tissue; injured cells underwent necrosis; as local inflammation continued, debris, fluid and dead and dying cells accumulated at the site as pus; and pus enclosed in a tissue space is an abscess.',
        rubric: ['Names abscess', 'Traces necrosis → pus → abscess', 'Identifies the triggering injury'] },
    ],
    commonMistakes: [
      'Assuming the alternative complement pathway is an equal substitute — the lecture says it is slower and less effective.',
      'Treating adaptive immunity as present at birth. It is acquired only after exposure or antibody transfer.',
    ],
    skills: [
      'The Latin sign list carries one false friend: tumor here is the sign meaning swelling — rubor, calor and dolor are its rhymed companions — not the English "tumour" of neoplasia, so reading the Latin through the English word plants a growth where the lecture claimed only a swollen tissue.',
      'Decide the complement pathway with one question — does it wait for an antibody? yes: classical, fast and effective; no: alternative, slower — then confirm both converge on C5–C9 to build the membrane attack complex.',
    ],
    selfCheck: 'From a blank page: the four signs with Latin names, the pathway decision with its reason, who made the antibody in active versus passive immunity, and the pus-in-an-enclosed-space trace back to the triggering injury.',
    sourceRefs: [{ ref: 'phys.10', location: 'Slides 27–35 complement system and pathways, inflammation, products of inflammation, forms of immunity; learning outcomes slide 2' }],
  },
  {
    id: 'hti17103-modality-best-use',
    subject: 'HTI17103', unit: 'hti.modalities', type: 'matching',
    title: 'What each modality is best used for',
    tags: ['modalities', 'high-yield'],
    lesson: {
      explanation: 'Each modality in the Week 2 lecture is introduced with the job it is suited to. Fluoroscopy provides real-time monitoring and is applicable intraoperatively, which is what makes it the choice for angiography, stent installation, bone cement work and function imaging of the digestive system. Mammography is presented as an extreme of resolution. Computed tomography exists because radiologists normally need two views and CT offers a 360-degree view; modern spiral CT adds multiplanar reconstruction and 3D angiographic reconstruction, up to a simulated heart model. Radionuclide imaging gives the non-invasive visualisation of bio-distribution, using a radiopharmaceutical made of a radioisotope plus a specific compound — the compound decides where it goes. MRI is summarised as giving good soft-tissue contrast, being compatible with function imaging and 3D/4D reconstruction, and being non-ionising. General X-ray, in its direct digital form, is the time-saving workhorse with no readers and no physical film.',
      keyFacts: [
        'Fluoroscopy — real-time, intraoperative: angiography, stent installation, bone cement, digestive function imaging.',
        'Mammography — an extreme of resolution.',
        'CT — a 360-degree view where two projections are not enough; multiplanar and 3D angiographic reconstruction.',
        'Radionuclide imaging — non-invasive visualisation of bio-distribution.',
        'MRI — good soft-tissue contrast, function imaging, 3D/4D, non-ionising.',
        'Direct digital radiography — no readers, time-saving, no physical films, but expensive.',
        'Contrast agents extend fluoroscopy: oral barium sulfate, or intravenous ionic vs non-ionic agents.',
      ],
      prerequisites: ['hti17103-ionizing-vs-nonionizing'],
      examples: [],
    },
    memory: {
      chunking: 'Sort by what the modality gives you that others cannot: time (fluoroscopy), resolution (mammography), a third dimension (CT), function and distribution (RNI), soft tissue without ionising radiation (MRI).',
      comparison: 'CT and MRI both give cross-sections. CT is fast and ionising; MRI has better soft-tissue contrast and no ionising radiation. If the question is about soft tissue, it is MRI.',
      mnemonic: 'Fluoroscopy is the only one that shows you *change over time*. Anything described as real-time or intraoperative is pointing at it.',
    },
    practice: [
      { type: 'matching', prompt: 'Match each modality to the capability the lecture highlights.',
        pairs: [['Fluoroscopy', 'Real-time monitoring, applicable intraoperatively'], ['Computed tomography', 'A 360-degree view with multiplanar reconstruction'], ['Magnetic resonance imaging', 'Good soft-tissue contrast, non-ionising'], ['Radionuclide imaging', 'Non-invasive visualisation of bio-distribution']],
        explanation: 'These are the defining capabilities each modality is introduced with in the Week 2 lecture.' },
      { type: 'mcq', prompt: 'A stent is being installed and the operator needs to watch it move into position. Which modality does the lecture point to?', options: ['Computed tomography', 'Fluoroscopy', 'Mammography', 'Magnetic resonance imaging'], answer: 1,
        explanation: 'Fluoroscopy — real-time monitoring, intraoperatively applicable, and stent installation is one of the listed applications.' },
      { type: 'typed', prompt: 'Which modality does the lecture describe as "an extreme of resolution"?', accept: ['mammography', 'mammogram'],
        explanation: 'Mammography.' },
      { type: 'comparison', prompt: 'CT and MRI both produce cross-sectional images. Which difference matters most when choosing between them?',
        options: [
          'MRI gives better soft-tissue contrast and uses no ionising radiation, while CT is an ionising modality',
          'CT cannot produce 3D reconstructions',
          'MRI is an ionising modality and CT is not',
          'They produce identical images by different means',
        ], answer: 0,
        explanation: 'Both give cross-sections, but the lecture puts CT in the ionising column and MRI in the non-ionising column, and summarises MRI as giving good soft-tissue contrast. Both can reconstruct in 3D.' },
    ],
    application: [
      { type: 'scenario', prompt: 'A radiopharmaceutical is described as a radioisotope combined with a specific compound. Which half decides what you can image, and why does that make radionuclide imaging different from CT?',
        model: 'The specific compound decides where the agent goes in the body, so it determines what you can image; the radioisotope only makes that distribution visible. That is what the lecture means by non-invasive visualisation of bio-distribution — RNI images function and where a substance travels, whereas CT images structure.',
        rubric: ['Identifies the compound as determining distribution', 'Identifies the isotope as providing the signal', 'Contrasts function/distribution with structure'] },
    ],
    commonMistakes: [
      'Choosing CT whenever cross-sections are wanted, without weighing the ionising-radiation difference against MRI.',
      'Forgetting that fluoroscopy is defined by being real-time, not by being an X-ray technique.',
    ],
    skills: [
      'Each modality owns exactly one capability the others lack — time (fluoroscopy), resolution (mammography), a third dimension (CT), function and distribution (radionuclide imaging), soft tissue without ionising radiation (MRI) — and the exam wording names the owner: "real-time" or "intraoperative" points at fluoroscopy, because being real-time, not being an X-ray technique, is its definition.',
      'CT and MRI are both cross-sectional, so the deciding difference is not the image shape but the column each sits in: CT is ionising, MRI gives better soft-tissue contrast without ionising radiation — and both reconstruct in 3D, so "cannot do 3D" is the false discriminator.',
      'A radiopharmaceutical is taxi and passenger: the specific compound decides where the agent goes and therefore what you can image; the radioisotope only makes that distribution visible — which is why radionuclide imaging reports function and bio-distribution where CT reports structure.',
    ],
    selfCheck: 'From a blank page: the matching of all four highlighted capabilities, the CT-versus-MRI decision with the ionising-radiation reason, and the stent scenario answered with the real-time modality.',
    sourceRefs: [{ ref: 'hti.w2', location: 'Slides 12–49 general X-ray cassettes, fluoroscopy and contrast enhancement, mammography, computed tomography, radiopharmaceuticals, RNI, MRI summary' }],
  },
];
