/* GENERATED by work/build-heart-alignment.mjs --write. Do not edit.
 * BetterHeart frame = ATLAS_SCALE * (dolasim.glb body frame) + ATLAS_SHIFT, no rotation.
 * Fitted over 39 same-named meshes; worst centre residual 0.0160.
 * The group in atlas.js therefore takes scale 1/ATLAS_SCALE and position -ATLAS_SHIFT/ATLAS_SCALE. */
export const ATLAS_SCALE = 24;
export const ATLAS_SHIFT = [-0.5521,-31.3689,-0.5998];
