/*
 * Data index generator — writes docs/DATA-INDEX.md.
 *
 * outputs/mesh-index.js is 141 KB of generated rows, and "what does the index
 * say about X" is the most common reason a session opens it. This is the
 * summary that answers the question the file was being opened for; anything
 * more specific is a work/query.mjs call.
 *
 * Usage: node work/data-index.mjs            # write docs/DATA-INDEX.md
 *        node work/data-index.mjs --stdout   # print it, write nothing
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MESH_INDEX, UNITS } from '../outputs/mesh-index.js';
import { SYNONYMS, COMPOSITES, NOT_MODELLED } from '../outputs/synonyms.js';
import { STUDY_ITEMS, SUBJECTS } from '../outputs/study-data.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = [];
const p = (s = '') => out.push(s);

const tally = (rows, key) => rows.reduce((m, r) => m.set(key(r), (m.get(key(r)) || 0) + 1), new Map());
const sorted = (m) => [...m.entries()].sort((a, b) => b[1] - a[1] || String(a[0]).localeCompare(String(b[0])));

p('<!-- GENERATED by work/data-index.mjs — do not edit. Run the script instead. -->');
p('# Data index');
p();
p('What the large generated files hold, so you never have to open them.');
p('For anything more specific: `node work/query.mjs <unit|mesh|item|layer> <term>`.');
p();

p('## `outputs/mesh-index.js` — GENERATED, never hand-edit');
p();
p(`${MESH_INDEX.length} structure rows resolving to ${UNITS.length} study units.`);
p('Rebuild: `node work/build-course-terms.mjs` (needs the Drive) then `node work/build-mesh-index.mjs`.');
p();
p('One row per named structure per layer, collapsed across side letters and');
p('Blender duplicate suffixes. Row shape:');
p();
p('```js');
p('{ name, layer, mesh, sides, tier, unitId, unit, unitKind, unitSize, isUnit,');
p('  source: { file, subject, evidence } | null }');
p('```');
p();
p('- `tier` — `0` the course names it, `1` finer than the course goes.');
p('- `unit` — what a tap actually selects. Every row resolves to one.');
p('- `sides` — `b` both, `l`, `r`, or `\'\'` unpaired.');
p('- `source` — non-null only for tier-0 rows; the course file that names it.');
p();
p('| Layer | Rows | Course-named (tier 0) |');
p('| --- | --- | --- |');
for (const [layer, n] of sorted(tally(MESH_INDEX, (r) => r.layer))) {
  const t0 = MESH_INDEX.filter((r) => r.layer === layer && r.tier === 0).length;
  p(`| ${layer} | ${n} | ${t0} |`);
}
p(`| **total** | **${MESH_INDEX.length}** | **${MESH_INDEX.filter((r) => r.tier === 0).length}** |`);
p();
p('| Unit kind | Count | Meaning |');
p('| --- | --- | --- |');
const KIND_MEANING = {
  course: 'the course names this structure — it is its own unit',
  group: 'finer than the course goes — folded into a named group',
  lone: 'one of a kind, with nothing to join',
};
for (const [kind, n] of sorted(tally(UNITS, (u) => u.kind))) {
  p(`| ${kind} | ${n} | ${KIND_MEANING[kind] || ''} |`);
}
p();
p('| Evidence | Rows | How the source names it |');
p('| --- | --- | --- |');
for (const [ev, n] of sorted(tally(MESH_INDEX.filter((r) => r.source), (r) => r.source.evidence))) {
  p(`| ${ev} | ${n} | |`);
}
p();

p('## `outputs/synonyms.js`');
p();
p(`- \`SYNONYMS\` — ${SYNONYMS.size} query expansions (collarbone→clavicle, CN X→vagus).`);
p(`- \`COMPOSITES\` — ${COMPOSITES.length} names with no mesh but real parts.`);
p(`  ${COMPOSITES.map((c) => c.name).sort().join(', ')}`);
p(`- \`NOT_MODELLED\` — ${NOT_MODELLED.length} things genuinely absent:`);
p(`  ${NOT_MODELLED.map((r) => r.term).sort().join(', ')}`);
p();
p('**Before writing a new `NOT_MODELLED` entry, check it against the index.**');
p('`work/search-probe.mjs` fails the build if a NOT_MODELLED term names a mesh that exists.');
p();

p('## `outputs/study-data.js` — the lesson corpus');
p();
p(`${STUDY_ITEMS.length} study items across ${SUBJECTS.length} subjects.`);
p();
p('| Subject | Units | Items |');
p('| --- | --- | --- |');
for (const s of SUBJECTS) {
  p(`| ${s.id} | ${(s.units || []).length} | ${STUDY_ITEMS.filter((i) => i.subject === s.id).length} |`);
}
p();
p('Item shape: `{ status, id, subject, unit, type, title, tags, lesson, memory,');
p('practice, application, commonMistakes, skills, selfCheck, sourceRefs }`.');
p();
p('| Item type | Count |');
p('| --- | --- |');
for (const [t, n] of sorted(tally(STUDY_ITEMS, (i) => i.type))) p(`| ${t} | ${n} |`);
p();

const text = `${out.join('\n')}\n`;
if (process.argv.includes('--stdout')) process.stdout.write(text);
else {
  writeFileSync(join(root, 'docs/DATA-INDEX.md'), text, 'utf8');
  console.log(`docs/DATA-INDEX.md — ${text.split('\n').length} lines`);
}
