/*
 * Where the curated route payloads live, and what they were derived from.
 *
 * One file per layer, fetched with the layer it belongs to: tube routes for the
 * travelling constriction, glow routes for the travelling light.
 *
 * GENERATED by work/build-physiology-paths.mjs — do not hand-edit. The `?g=`
 * stamp is the cache key: it changes whenever the generator, the path kernel,
 * the route definitions or the model version change, so a regenerated payload
 * is a new URL rather than a stale entry in the model cache.
 */
export const PATH_STAMP = '4081ec70a3a3';
export const PATH_PAYLOADS = {
  organs: { url: './assets/physiology/organs-paths.json?g=4081ec70a3a3', bytes: 246978, routes: 6, rejected: 3 },
  circulatory: { url: './assets/physiology/circulatory-paths.json?g=4081ec70a3a3', bytes: 52671, routes: 40, rejected: 4 },
  nervous: { url: './assets/physiology/nervous-paths.json?g=4081ec70a3a3', bytes: 7368, routes: 6, rejected: 2 },
};
