/*
 * Where the curated route payloads live, and what they were derived from.
 *
 * One file per layer, fetched with the layer it belongs to: tube routes for the
 * travelling constriction, pulse frames for arterial swell, glow for light.
 *
 * GENERATED by work/build-physiology-paths.mjs — do not hand-edit. The `?g=`
 * stamp is the cache key: it changes whenever the generator, the path kernel,
 * the route definitions or the model version change, so a regenerated payload
 * is a new URL rather than a stale entry in the model cache.
 */
export const PATH_STAMP = 'a2ff0d212c71';
export const PATH_PAYLOADS = {
  organs: { url: './assets/physiology/organs-paths.json?g=a2ff0d212c71', bytes: 247058, routes: 6, rejected: 3 },
  circulatory: { url: './assets/physiology/circulatory-paths.json?g=a2ff0d212c71', bytes: 158605, routes: 40, rejected: 4 },
  nervous: { url: './assets/physiology/nervous-paths.json?g=a2ff0d212c71', bytes: 7448, routes: 6, rejected: 2 },
};
