/*
 * Where the curated tube-route payloads live, and what they were derived from.
 *
 * GENERATED by work/build-physiology-paths.mjs — do not hand-edit. The `?g=`
 * stamp is the cache key: it changes whenever the generator, the path kernel,
 * the route definitions or the model version change, so a regenerated payload
 * is a new URL rather than a stale entry in the model cache.
 */
export const PATH_STAMP = 'cb0f0270e737';
export const PATH_PAYLOADS = {
  organs: { url: './assets/physiology/organs-paths.json?g=cb0f0270e737', bytes: 246587, routes: 6, rejected: 3 },
};
